import type { Source } from "@/types/content";

/**
 * Works cited in BELDAR_RESEARCH.md. `n` matches the bracketed citation
 * number in the research. "supports" summarizes where the research leans on it.
 */
export const sources: Source[] = [
  { id: "s1", n: 1, title: "How to Make Foam Latex For Masks, Puppets & Prosthetics", publisher: "Mouldlife", url: "https://www.mouldlife.net/foam-latex-guide-318-c.asp", category: "manufacturer", reliability: "manufacturer", supports: "Foam latex needs ovens and controlled curing — why we don't do it at home." },
  { id: "s2", n: 2, title: "Art the Clown Prosthetic Guide", publisher: "Reddit r/cosplayers", url: "https://www.reddit.com/r/cosplayers/comments/1omza6c/art_the_clown_prosthetic_guide/", category: "community", reliability: "community", supports: "Foam latex is hot, traps sweat and breaks down at the edges." },
  { id: "s3", n: 3, title: "Gelatine", publisher: "clairegolbymue (Wix)", url: "https://miss07murder.wixsite.com/clairegolbymue/gelatine", category: "sfx-technique", reliability: "community", supports: "Gelatin appliances melt with body heat and sweat." },
  { id: "s4", n: 4, title: "A to Z Tabletop Prosthetics Part 2: Demold, Cast, Apply & Paint", publisher: "Stan Winston School", url: "https://www.stanwinstonschool.com/tutorials/a-to-z-tabletop-prosthetics-part-2-demold-cast-apply-paint-prosthetic-makeup-appliances", category: "sfx-technique", reliability: "professional", supports: "Silicone appliances; bald cap adhesion, Pros-Aide wait times, tension management." },
  { id: "s5", n: 5, title: "Encapsulated Pros-Aide Prosthetics Part 1: Sculpting, Molding", publisher: "Stan Winston School", url: "https://www.stanwinstonschool.com/tutorials/encapsulated-pros-aide-prosthetics-part-1-sculpting-molding-casting", category: "sfx-technique", reliability: "professional", supports: "Pro-level encapsulated method cost and complexity." },
  { id: "s6", n: 6, title: "Cone Pattern — Digital Download", publisher: "Kamui Cosplay", url: "https://www.kamuicosplay.com/product/conepattern/", category: "sfx-technique", reliability: "professional", supports: "EVA foam cone patterning; 4–5mm EVA as shell material." },
  { id: "s7", n: 7, title: "T.V. How to Apply Bald Caps", publisher: "Michael Davy Film", url: "http://www.michaeldavy.com/howto/howto_baldcap.html", category: "sfx-technique", reliability: "professional", supports: "Glatzan application with Pros-Aide and acetone-melted edges." },
  { id: "s8", n: 8, title: "History of The Bald Cap", publisher: "Scribd", url: "https://www.scribd.com/document/1063747871/History-of-the-Bald-Cap", category: "prosthetics", reliability: "community", supports: "Vinyl vs latex cap edges; acetone melts vinyl." },
  { id: "s9", n: 9, title: "How do you design and deal with exaggerated large, tall headpieces", publisher: "Reddit r/cosplayprops", url: "https://www.reddit.com/r/cosplayprops/comments/dhsa8l/help_how_do_you_design_and_deal_with_exaggerated/", category: "community", reliability: "community", supports: "Weight, leverage and neck fatigue of tall headpieces." },
  { id: "s10", n: 10, title: "Liquid Latex Makeup: How to Use It, and What to Use Instead", publisher: "The Face Paint Shop", url: "https://www.thefacepaintshop.com/blogs/all-blogs/liquid-latex-makeup-how-to-use-it-and-latex-free-alternatives", category: "sfx-technique", reliability: "retail", supports: "Liquid latex sealing; latex-free alternatives for allergies." },
  { id: "s11", n: 11, title: "Good brand for bald cap?", publisher: "Facebook SFX group", url: "https://www.facebook.com/groups/500656300020100/posts/6161999143885759/", category: "community", reliability: "community", supports: "Latex caps leave a visible ridge that can't be dissolved." },
  { id: "s12", n: 12, title: "Super-Cap — Encapsulant isopropyl alcohol for prosthetics", publisher: "Feroca", url: "https://feroca.com/en/cap-plastics-encapsulants/630-super-cap-encapsulant-isopropyl-alcohol-for-prosthetics-.html", category: "manufacturer", reliability: "retail", supports: "Super Baldiez / IPA-melt pro method." },
  { id: "s13", n: 13, title: "Coneheads Beldar (Dan Aykroyd) Conehead Prosthetic Head", publisher: "iCollector / Hollywood auction listing", url: "https://www.icollector.com/Coneheads-Beldar-Dan-Aykroyd-Conehead-Prosthetic-Head_i16466501", category: "film-reference", reliability: "primary", supports: "Screen-used appliance: ~16\" tall × 10\" wide flattened; production artists." },
  { id: "s14", n: 14, title: "The Icons & Legends of Hollywood Auction 112 (full text)", publisher: "Internet Archive", url: "https://archive.org/stream/a-112-icons-2-l/A112Icons2L_djvu.txt", category: "film-reference", reliability: "primary", supports: "No eyebrows; communicator-style prop." },
  { id: "s15", n: 15, title: "Vinyl or latex bald cap for a Shrek costume?", publisher: "Reddit r/sfx", url: "https://www.reddit.com/r/sfx/comments/179apz2/vinyl_or_latex_bald_cap_for_a_shrek_costume/", category: "community", reliability: "community", supports: "Forehead transition behind the ears; ear left exposed." },
  { id: "s16", n: 16, title: "Ian Talks Comedy (podcast feed)", publisher: "Spotify for Creators", url: "https://anchor.fm/s/21d579e4/podcast/rss", category: "film-reference", reliability: "tangential", supports: "Production anecdote context (weak source)." },
  { id: "s17", n: 17, title: "Painting Latex & Foam Latex", publisher: "Stuart Bray / Battles With Bits Of Rubber (PDF)", url: "https://battleswithbitsofrubber.com/wp-content/uploads/2020/04/BWBOR_painting_latex_and_foam_latex.pdf", category: "sfx-technique", reliability: "professional", supports: "PAX paint, powdering PAX tack, PAX + RMGP workflow." },
  { id: "s18", n: 18, title: "Pros-Aide formula by ADM Tronics, medical-grade skin adhesive", publisher: "sympozjum.com.pl (reseller page)", url: "https://www.sympozjum.com.pl/Formula-By-ADM-Tronics-Medical-Grade-Skin-Adhesive-Goes-On-242688/", category: "manufacturer", reliability: "tangential", supports: "Pros-Aide product background (weak source)." },
  { id: "s19", n: 19, title: "Kryolan Rubber Mask Grease Palette — Pro", publisher: "Holly North", url: "https://hollynorth.com/product/rmg-palette/", category: "manufacturer", reliability: "retail", supports: "RMGP is castor-oil based and safe over rubber; organic mottling." },
  { id: "s20", n: 20, title: "Adhesives and Cleansers", publisher: "Stage Makeup Online", url: "https://stagemakeuponline.com/collections/adhesives-and-cleaners", category: "shopping", reliability: "retail", supports: "Pros-Aide over spirit gum." },
  { id: "s21", n: 21, title: "Pax Paint Recipe for SFX Makeup", publisher: "Facebook answers", url: "https://www.facebook.com/fb-answers/pax-paint-recipe-for-sfx-makeup/?locale=cs_CZ", category: "community", reliability: "community", supports: "PAX = Pros-Aide + acrylic; flexible, crack-resistant." },
  { id: "s22", n: 22, title: "Barge All-Purpose Cement — Safety Data Sheet", publisher: "Barge Cements / Weaver Brands", url: "https://www.weaverbrands.com/docs/default-source/sds/barge-all-purpose-cement-3-4-oz-.pdf?sfvrsn=34962ba0_11", category: "manufacturer", reliability: "manufacturer", supports: "Barge bonds EVA permanently; VOC hazards." },
  { id: "s23", n: 23, title: "Gravity Cosplay Headgear (Etsy listing)", publisher: "Etsy", url: "https://www.etsy.com/listing/4365012177/ochaco-uraraka-cosplay-headgear", category: "community", reliability: "tangential", supports: "General cosplay headgear construction (weak source)." },
  { id: "s24", n: 24, title: "I made Diablo's Head using EVA Foam & Foam Clay!", publisher: "YouTube", url: "https://www.youtube.com/watch?v=o9Gi-2WO38g", category: "sfx-technique", reliability: "community", supports: "Foam clay dome sculpting; 24–48h air-dry." },
  { id: "s25", n: 25, title: "Propmaking Materials catalogue", publisher: "Flints Theatre Chandlers", url: "https://www.flints.co.uk/catalogue/_fs2526_Propmaking%20Materials.pdf", category: "shopping", reliability: "retail", supports: "Propmaking material availability." },
  { id: "s26", n: 26, title: "Mask Paint — Latex paint from Monster Makers", publisher: "Feroca", url: "https://feroca.com/en/latex-complements/663-mask-paint-latex-paint-from-monster-makers-.html", category: "manufacturer", reliability: "retail", supports: "Flexible primers for foam (HexFlex-type)." },
  { id: "s27", n: 27, title: "TMNT's Leatherhead (forum thread)", publisher: "Stan Winston School Forums", url: "https://forums.stanwinstonschool.com/discussion/9658/tmnts-leatherhead", category: "community", reliability: "community", supports: "Foam headpiece build discussion." },
  { id: "s28", n: 28, title: "Kryolan Glatzan Bald Caps", publisher: "Don's Costume & Make Up Shop", url: "https://costumeandmakeupshop.ca/products/kryolan-glatzan-bald-cap", category: "shopping", reliability: "retail", supports: "Glatzan cap; hair flattening; trimming with gluing margin." },
  { id: "s29", n: 29, title: "Cone (truncated) — Free Custom Template", publisher: "Templatemaker.nl", url: "https://www.templatemaker.nl/en/cone/", category: "sfx-technique", reliability: "professional", supports: "Frustum pattern generator from r1, r2, h." },
  { id: "s30", n: 30, title: "Dome Cover Calculator", publisher: "Domerama", url: "http://www.domerama.com/calculators/cover-pattern/", category: "sfx-technique", reliability: "community", supports: "Alternate cone/dome pattern geometry." },
  { id: "s31", n: 31, title: "How do I print patterns for the right size?", publisher: "Reddit r/cosplayprops", url: "https://www.reddit.com/r/cosplayprops/comments/17csa5a/how_do_i_print_pattenrs_for_the_right_size/", category: "community", reliability: "community", supports: "Why a paper template test is mandatory." },
  { id: "s32", n: 32, title: "Does 99% alcohol dissolve acetone-based cap plastic in silicone?", publisher: "Facebook SFX group", url: "https://www.facebook.com/groups/500656300020100/posts/24551809624478098/", category: "community", reliability: "community", supports: "IPA melts Super Baldiez edges." },
  { id: "s33", n: 33, title: "Alcohol activated vs. grease paint — best practices", publisher: "Reddit r/sfx", url: "https://www.reddit.com/r/sfx/comments/1fru86e/alcohol_activated_vs_grease_paint_seeking_best/", category: "community", reliability: "community", supports: "Paint system choice over rubber." },
  { id: "s34", n: 34, title: "Mehron SKIN Prep PRO (formerly \"No Sweat\")", publisher: "Camera Ready Cosmetics", url: "https://camerareadycosmetics.com/products/mehron-skin-prep-pro-formerly-no-sweat", category: "manufacturer", reliability: "retail", supports: "Antiperspirant barrier extends adhesive life." },
  { id: "s35", n: 35, title: "Best and fastest options for removing Pros-Aide", publisher: "Facebook SFX group", url: "https://www.facebook.com/groups/500656300020100/posts/8092195344199453/", category: "community", reliability: "community", supports: "Micellar water/soap don't remove Pros-Aide." },
  { id: "s36", n: 36, title: "The ONLY EVA Foam Cosplay Starter Guide You'll Ever Need", publisher: "YouTube", url: "https://www.youtube.com/watch?v=txFoQDyePY0", category: "sfx-technique", reliability: "community", supports: "Sharp blades at 90°, heat shaping EVA." },
  { id: "s37", n: 37, title: "Is it safe to work with contact cement without a mask?", publisher: "Reddit r/cosplayprops", url: "https://www.reddit.com/r/cosplayprops/comments/1h64v97/is_it_safe_to_work_with_contact_cement_glue/", category: "community", reliability: "community", supports: "Respirator + ventilation for contact cement." },
  { id: "s38", n: 38, title: "Adhesives That Won't Dissolve Your Foam", publisher: "Taylor Theatrics", url: "https://taylortheatrics.com/2018/08/01/foam-adhesives-that-wont-dissolve-your-foam/", category: "sfx-technique", reliability: "professional", supports: "Contact cement bonds instantly; no realignment." },
  { id: "s39", n: 39, title: "Sticky Situations — The Zen of Prosthetic Adhesives & Removers", publisher: "Learn Makeup Effects", url: "http://www.learnmakeupeffects.com/sticky-situations-the-zen-of-prosthetic-adhesives-removers/", category: "sfx-technique", reliability: "professional", supports: "Wait for Pros-Aide to turn clear; roll-and-brush removal." },
  { id: "s40", n: 40, title: "Casualty Simulation Techniques", publisher: "Virginia Department of Health (PDF)", url: "https://www.vdh.virginia.gov/content/uploads/sites/23/2016/05/PRE-025-CasualtySimulationTechniques.pdf", category: "sfx-technique", reliability: "professional", supports: "PAX mixing ratio context." },
  { id: "s41", n: 41, title: "Casualty Simulation Techniques", publisher: "barrymrobinson.ca (PDF)", url: "https://www.barrymrobinson.ca/downloads/casualty_simulation_techniques.pdf", category: "sfx-technique", reliability: "professional", supports: "Moulage paint technique context." },
  { id: "s42", n: 42, title: "Beldar Wardrobe — Coneheads (1993), original screen-used", publisher: "YourProps", url: "https://yourprops.com/beldar-wardrobe-costumes-original-screen-used-coneheads-yp843759", category: "wardrobe", reliability: "primary", supports: "Fireworks-scene casual look vs gray jumpsuits." },
  { id: "s43", n: 43, title: "Liberty Men's Rigid Denim Bib Overalls", publisher: "Tractor Supply Co", url: "https://www.tractorsupply.com/tsc/product/liberty-mens-rigid-bib-overall", category: "shopping", reliability: "retail", supports: "Liberty overalls (green zipper accents); price range." },
  { id: "s44", n: 44, title: "Liberty Mens Coveralls", publisher: "Walmart.com", url: "https://www.walmart.com/browse/clothing/mens-work-coveralls/liberty/5438_133197_2375443_6526879/YnJhbmQ6TGliiZXJ0eQieie", category: "shopping", reliability: "retail", supports: "Liberty availability." },
  { id: "s45", n: 45, title: "Round House Bib Overall Care and Fit Guide", publisher: "Round House", url: "https://www.roundhouseoutlet.com/pages/bib-overalls-care-fit-guide-2", category: "wardrobe", reliability: "manufacturer", supports: "Size by belly; add 4–6\" to jean waist." },
  { id: "s46", n: 46, title: "Mens 90s Rayon Shirts", publisher: "Etsy", url: "https://www.etsy.com/market/mens_90s_rayon_shirts?page=4", category: "shopping", reliability: "retail", supports: "Rayon drape under overall straps." },
  { id: "s47", n: 47, title: "Natural Issue Button-Down Shirts for Men", publisher: "eBay", url: "https://www.ebay.com/b/Natural-Issue-Floral-Button-Up-Casual-Button-Down-Shirts-for-Men/57990/bn_4764492", category: "shopping", reliability: "retail", supports: "Natural Issue vintage shirt availability." },
  { id: "s48", n: 48, title: "90s Geometric Pattern Shirt Mens (p.4)", publisher: "Etsy", url: "https://www.etsy.com/market/90s_geometric_pattern_shirt_mens?page=4", category: "shopping", reliability: "retail", supports: "Memphis / jazz-cup pattern; price range." },
  { id: "s49", n: 49, title: "90s Geometric Pattern Shirt Mens", publisher: "Etsy", url: "https://www.etsy.com/market/90s_geometric_pattern_shirt_mens", category: "shopping", reliability: "retail", supports: "Vintage geometric shirt listings." },
  { id: "s50", n: 50, title: "Vintage Abstract Shirt", publisher: "eBay", url: "https://www.ebay.com/shop/vintage-abstract-shirt?_nkw=vintage+abstract+shirt", category: "shopping", reliability: "retail", supports: "Brands: Natural Issue, Campia Moda, Perry Ellis, Jhane Barnes." },
  { id: "s51", n: 51, title: "Men's Vintage Casual Shirts", publisher: "PicClick", url: "https://picclick.com/Clothing-Shoes-Accessories/Specialty/Vintage/Mens-Vintage-Clothing/Casual-Shirts/", category: "shopping", reliability: "retail", supports: "Vintage shirt marketplace." },
  { id: "s52", n: 52, title: "How To Patch Test New Products Safely", publisher: "Acrylate Allergy", url: "https://www.acrylateallergy.com/how-to-patch-test-new-products/", category: "prosthetics", reliability: "professional", supports: "24-hour adhesive patch test." },
  { id: "s53", n: 53, title: "Mehron Skin Prep Pro (Mattifying Skin Toner) 120ml", publisher: "Hokey Pokey Shop", url: "https://www.hokeypokeyshop.ca/skin-prep-pro-no-sweat-120ml", category: "shopping", reliability: "retail", supports: "Skin Prep Pro availability." },
  { id: "s54", n: 54, title: "Prosthetic Adhesive & Removers", publisher: "Mouldlife", url: "https://www.mouldlife.net/prosthetic-adhesive--removers-106-c.asp", category: "manufacturer", reliability: "manufacturer", supports: "Super Solv and Isopropyl Myristate removers." },
  { id: "s55", n: 55, title: "Best Pros-Aide removal?", publisher: "Reddit r/makeupeffects", url: "https://www.reddit.com/r/makeupeffects/comments/17n9zhs/best_prosaide_removal/", category: "community", reliability: "community", supports: "Wipes and soap are ineffective on Pros-Aide." },
  { id: "s56", n: 56, title: "How to Work with Latex, Silicone and Prosthetics Safely", publisher: "Cinema Makeup School", url: "https://www.cinemamakeup.com/blogs/how-to-safely-work-with-latex-silicone-prosthetics/", category: "prosthetics", reliability: "professional", supports: "Post-removal skin aftercare." },
  { id: "s57", n: 57, title: "Patch Testing", publisher: "FHSU student project", url: "https://www.haharper.infprojects.fhsu.edu/finalproject/patchtesting.html", category: "prosthetics", reliability: "community", supports: "Patch testing background." },
  { id: "s58", n: 58, title: "Pros-Aide Cream Medical-Grade Prosthetic Adhesive", publisher: "Feroca", url: "https://feroca.com/en/human-body-stickers/907-pros-aide-cream-medical-grade-adhesive.html", category: "manufacturer", reliability: "retail", supports: "Filling a visible ridge with Pros-Aide Cream." },
  { id: "s59", n: 59, title: "Kryolan Special Effects", publisher: "FormX", url: "https://www.formx.nl/p/category/8f129acd-dd51-48e9-bf97-ced114499bd6?setlanguage=en", category: "manufacturer", reliability: "retail", supports: "Acetone melt technique for Glatzan." },
];

export const sourceById = Object.fromEntries(sources.map((s) => [s.id, s])) as Record<string, Source>;

export const sourceCategoryLabels: Record<Source["category"], string> = {
  "film-reference": "Film reference",
  wardrobe: "Wardrobe",
  prosthetics: "Prosthetics",
  manufacturer: "Manufacturer",
  "sfx-technique": "SFX technique",
  shopping: "Shopping",
  "reference-image": "Reference image",
  community: "Community / secondary",
};

export const reliabilityLabels: Record<Source["reliability"], { label: string; note: string }> = {
  primary: { label: "Primary", note: "Auction/archive records of screen-used items" },
  manufacturer: { label: "Manufacturer", note: "Maker's guide or safety data sheet" },
  professional: { label: "Professional", note: "SFX school, pro tutorial or trade reference" },
  retail: { label: "Retailer", note: "Product listing; good for specs, not technique" },
  community: { label: "Community", note: "Forum or hobbyist advice — corroborate" },
  tangential: { label: "Weak / tangential", note: "Cited by the research but only loosely related" },
};

/** External reference links from the research's Image Reference Manifest. */
export const imageManifest = [
  { target: "Screen-used prosthetic", source: "Propstore archives / auction listing", sourceId: "s13", url: "https://www.icollector.com/Coneheads-Beldar-Dan-Aykroyd-Conehead-Prosthetic-Head_i16466501", demonstrates: "Exact taper, 16×10\" flattened dimensions, foam texture.", reliability: "confirmed", use: "Safe external link for fabrication reference." },
  { target: "Fireworks scene costume", source: "Film stills (Paramount 1993)", sourceId: "s42", url: "https://yourprops.com/beldar-wardrobe-costumes-original-screen-used-coneheads-yp843759", demonstrates: "Liberty overalls drape, rayon shirt pattern.", reliability: "confirmed", use: "Private reference only — do not redistribute stills. Put your own copies in /public/references (git-ignored)." },
  { target: "Acetone melt technique", source: "Kryolan / FormX tutorials", sourceId: "s59", url: "https://www.formx.nl/p/category/8f129acd-dd51-48e9-bf97-ced114499bd6?setlanguage=en", demonstrates: "The invisible edge achievable with Glatzan and acetone.", reliability: "strongly-supported", use: "Safe external link to SFX tutorial." },
  { target: "Bald cap application", source: "Stan Winston School", sourceId: "s4", url: "https://www.stanwinstonschool.com/tutorials/a-to-z-tabletop-prosthetics-part-2-demold-cast-apply-paint-prosthetic-makeup-appliances", demonstrates: "Proper adhesion, Pros-Aide wait times, tension management.", reliability: "confirmed", use: "Safe external link to educational material." },
  { target: "Frustum geometry", source: "Templatemaker.nl", sourceId: "s29", url: "https://www.templatemaker.nl/en/cone/", demonstrates: "How to calculate arc lengths from radii for EVA foam.", reliability: "strongly-supported", use: "Formula embedded in Cone Lab; link to generator for printable tiles." },
] as const;
