import type { Task } from "@/types/content";

/**
 * Build tasks. Where a task maps to the research's Master Checklist the
 * `checklistId` is set and duration/cost/difficulty/helper come from that
 * table. Instructions are taken from the research's procedure sections.
 */
export const tasks: Task[] = [
  // ── PH-00 Intel & Measurements ──────────────────────────────────────
  {
    id: "t-references", phaseId: "intel", title: "Study the Beldar silhouette",
    summary: "Look at the screen-used appliance reference and agree on what you're building.",
    why: "The most common failure is a cone that reads as a wizard hat or traffic cone. Knowing the real shape prevents it.",
    instructions: [
      "Open the screen-used prosthetic reference (auction listing) and the Cone Lab front/side diagrams.",
      "Note: the shape is a smooth, elongated parabolic curve — not a mathematically perfect, sharp-tipped cone.",
      "Note: the profile leans very slightly backward toward the back of the head.",
      "Note: the forehead transition sits just above the natural brow ridge and curves down behind the ears, leaving the ears exposed.",
      "Note: Beldar has no eyebrows, pale slightly jaundiced translucent skin, subtle mottling, faint blue/red capillaries at the temples, and a highlight on the front of the cone.",
      "The auctioned appliance measures ~16\" tall × 10\" wide — but that is flattened and unmounted. Do not scale it directly.",
    ],
    prerequisites: [], materialIds: [], toolIds: [], durationLabel: "20 min", durationMinutes: 20, difficulty: 1, helper: "solo",
    watchOut: ["Blindly scaling the 16\" measurement produces a comically oversized, unstable piece."],
    completionCriteria: ["Everyone can describe the target: parabolic dome, slight backward lean, ears exposed, no eyebrows."],
    confidence: "confirmed", sourceIds: ["s13", "s14", "s15"],
    referenceLink: { label: "Screen-used appliance (auction listing)", url: "https://www.icollector.com/Coneheads-Beldar-Dan-Aykroyd-Conehead-Prosthetic-Head_i16466501" },
  },
  {
    id: "t-measure", checklistId: "001", phaseId: "intel", title: "Measure the head & calculate the pattern",
    summary: "Measure head circumference and calculate the frustum pattern.",
    why: "The circumference dictates the bottom arc. If it's wrong, the internal support won't grip and the cone wobbles — generic templates guarantee a poor fit.",
    instructions: [
      "Use a flexible tailor's tape.",
      "Head circumference (C): horizontally around the cranium, directly over the brow ridge and just above the ears.",
      "Forehead width: horizontal distance between the temples.",
      "Ear-to-ear over crown: from the top of the left ear, over the top of the skull, to the top of the right ear.",
      "Desired finished cone height (h): vertical height from the brow line — about 10–11\".",
      "Enter the numbers in Cone Lab. It computes base radius r₁ = C / (2π) with a top radius r₂ of 1.5–2\", then the arc lengths.",
    ],
    measurement: "r₁ = C / (2π) · r₂ = 1.5–2\" · h ≈ 10–11\"",
    prerequisites: [], materialIds: [], toolIds: ["tape-measure"], durationLabel: "30 mins", durationMinutes: 30, costLabel: "$0", difficulty: 2, helper: "solo",
    watchOut: ["Tape must pass over the brow ridge and just above the ears — not around the forehead higher up."],
    completionCriteria: ["Formula outputs valid radii."],
    confidence: "strongly-supported", sourceIds: ["s29"],
    referenceLink: { label: "Open Cone Lab", url: "/cone-lab" },
  },
  {
    id: "t-allergy", phaseId: "intel", title: "Latex & adhesive allergy check",
    summary: "Ask the wearer and the fabricators about latex allergies before ordering.",
    why: "A latex allergy changes the sealant (HexFlex/PlastiDip instead of liquid latex) and the sponges you buy.",
    instructions: [
      "Ask the wearer and anyone handling materials whether they have a known latex allergy.",
      "If yes: substitute a synthetic sealant (PlastiDip or HexFlex) for liquid latex and use polyurethane sponges only.",
      "Either way, a 24-hour Pros-Aide patch test is still mandatory later (Gate 3).",
    ],
    prerequisites: [], materialIds: ["latex-alt"], toolIds: [], durationLabel: "5 min", durationMinutes: 5, difficulty: 1, helper: "solo",
    warningIds: ["w-latex"], watchOut: [], completionCriteria: ["Allergy status known; sealant choice made."],
    confidence: "confirmed", sourceIds: ["s10"],
  },
  {
    id: "t-eyebrows", phaseId: "intel", title: "Decide the eyebrow plan",
    summary: "Beldar has no eyebrows: block them with prosthetic wax or shave them.",
    why: "The research says the missing eyebrows are part of the look and require either aggressive blocking or shaving.",
    instructions: [
      "Choose between blocking the natural brows with prosthetic wax or shaving them before application.",
      "The vinyl skirt is pulled down over the eyebrows during fitting either way.",
    ],
    prerequisites: [], materialIds: [], toolIds: [], durationLabel: "5 min", durationMinutes: 5, difficulty: 1, helper: "solo",
    watchOut: ["Research gap: no brow-blocking procedure or wax product is specified. If you choose wax, test it during Prototype 2."],
    completionCriteria: ["Decision recorded in the build log."],
    confidence: "research-gap", sourceIds: ["s14"],
  },

  // ── PH-01 Acquisition ───────────────────────────────────────────────
  {
    id: "t-order-sfx", checklistId: "002", phaseId: "acquire", title: "Order SFX materials",
    summary: "Order Glatzan cap, Pros-Aide, PAX ingredients, RMGP, Skin Prep Pro and remover.",
    why: "Specialty SFX items gate the patch test, PAX mixing and the acetone-melt practice.",
    instructions: [
      "Open Materials, filter to the Recommended tier, and order: Kryolan Glatzan cap (Large), Pros-Aide (2 oz), Liquitex Heavy Body (Titanium White, Yellow Ochre, Burnt Sienna), Kryolan RMGP palette, translucent setting powder, Mehron Skin Prep Pro, Telesis Super Solv, 100% acetone.",
      "Mark each item 'Ordered' and record the actual price.",
      "Consider whether you want a spare Glatzan for the Prototype 2 practice and future re-use (the vinyl skirt is usually destroyed on removal).",
    ],
    prerequisites: [], materialIds: ["glatzan", "pros-aide", "liquitex", "rmgp", "setting-powder", "skin-prep", "super-solv", "acetone"], toolIds: [],
    durationLabel: "1 hr", durationMinutes: 60, costLabel: "~$120", difficulty: 1, helper: "solo",
    watchOut: ["Prices are Q3 2026 estimates; specialty chemicals are volatile."],
    completionCriteria: ["All items in transit."],
    sourceIds: [], referenceLink: { label: "Open Materials", url: "/materials" },
  },
  {
    id: "t-order-fab", phaseId: "acquire", title: "Buy fabrication supplies & tools",
    summary: "EVA foam, foam clay, Barge, liquid latex, respirator, heat gun, blades, cutting mat.",
    why: "These aren't in checklist 002 but the cone can't be built without them.",
    instructions: [
      "From Materials: 5mm high-density EVA roll, 300g air-dry foam clay, Barge contact cement (quart), liquid latex 16 oz (or HexFlex if latex-allergic).",
      "Tools referenced by the procedure: organic vapor respirator, heat gun, sharp utility knife/scalpel + spare blades, cutting mat, high-grit sandpaper, a curved form (large pot or mannequin head).",
      "Prototype kits: cardstock + masking tape; cheap EVA floor mats + hot glue (if doing Prototype 1).",
    ],
    prerequisites: [], materialIds: ["eva-foam", "foam-clay", "barge", "liquid-latex", "cardstock", "proto-foam"], toolIds: ["respirator", "heat-gun", "knife", "cutting-mat", "sandpaper", "form"],
    durationLabel: "1 hr", durationMinutes: 60, costLabel: "~$80 + tools", difficulty: 1, helper: "solo",
    watchOut: ["The respirator is not optional for Barge."],
    completionCriteria: ["Fabrication supplies on hand."], sourceIds: [],
  },

  // ── P-0 Paper Silhouette ────────────────────────────────────────────
  {
    id: "t-paper", checklistId: "004", phaseId: "proto0", title: "Build the paper template (Prototype 0)",
    summary: "Test the frustum math with a cardstock prototype.",
    why: "Heads are oval, not cylindrical. A paper test is absolutely mandatory to verify fit and proportions before cutting foam.",
    instructions: [
      "Print or draw the frustum pattern from Cone Lab onto heavy cardstock (Templatemaker.nl can generate a tiled printable template from your r₁, r₂, h).",
      "Cut it out and tape the straight edges together with masking tape.",
      "Set it on the wearer's head. It should clear the cranial ridge and sit flush against the forehead.",
      "Look at it from the front and side. Does it read as Beldar?",
    ],
    measurement: "Bottom arc length = your head circumference C",
    prerequisites: ["t-measure"], materialIds: ["cardstock"], toolIds: [], durationLabel: "45 mins", durationMinutes: 45, costLabel: "$2", difficulty: 2, helper: "recommended",
    watchOut: ["If it falls off or wobbles, re-measure circumference before going further."],
    completionCriteria: ["Paper cone fits flush.", "The paper cone rests securely on the head without holding it."],
    confidence: "requires-prototyping", sourceIds: ["s29", "s31"],
    referenceLink: { label: "Templatemaker.nl truncated cone", url: "https://www.templatemaker.nl/en/cone/" },
  },

  // ── P-1 Structural Prototype ────────────────────────────────────────
  {
    id: "t-proto1", phaseId: "proto1", title: "Build the cheap structural cone (Prototype 1)",
    summary: "Foam-mat cone with hot glue to test balance and the internal support band.",
    why: "Verifies center of gravity, balance and the friction-fit support mechanism before you commit good foam and Barge.",
    instructions: [
      "Cut the validated pattern from cheap EVA anti-fatigue floor mats.",
      "Hold the seam with hot glue (temporary).",
      "Add a 2\" wide band of foam inside as the internal cradle around the cranial ridge (just above the ears and brow bone).",
      "Wearer walks around. Watch the tilt.",
      "If the cone tilts backward when walking, recut the base angle until it sits perfectly parallel to the ground (plumb).",
    ],
    prerequisites: ["t-paper"], materialIds: ["proto-foam"], toolIds: ["knife", "cutting-mat"], durationLabel: "2 hrs", durationMinutes: 120, costLabel: "$10", difficulty: 2, helper: "recommended",
    watchOut: ["Base patterned completely flat instead of matching the skull slope → tilts backward."],
    completionCriteria: ["Cone sits plumb while walking.", "Support band grips without straps."],
    confidence: "requires-prototyping", sourceIds: ["s9"],
  },

  // ── PH-02 Master Cone Fabrication ───────────────────────────────────
  {
    id: "t-cut-heat", checklistId: "005", phaseId: "fabricate", title: "Pattern, cut & heat-form the EVA",
    summary: "Transfer pattern to 5mm EVA, cut, and heat-curve.",
    why: "Clean cuts and pre-formed curvature mean a seam that's easy to hide and low stress on the glue line.",
    instructions: [
      "Patterning: transfer the frustum template onto the 5mm EVA. If cut from a rolled mat, align the foam's natural curve with the horizontal curve of the cone pattern.",
      "Choose the layout: one continuous piece joined at the rear, or two symmetrical halves joined at the sides.",
      "Cutting: use a highly sharpened utility knife or scalpel held at a strict 90° to the cutting mat. Change blades frequently.",
      "Heat shaping: warm the foam evenly with the heat gun until the surface is slightly glossy and pliable.",
      "Form the hot foam around a curved surface (a large pot or mannequin head) to set conical memory. Let it cool completely while held in shape.",
    ],
    measurement: "Top opening ≈ 3–4\" diameter (top radius 1.5–2\") — do not close to a point",
    prerequisites: ["t-paper", "t-order-fab"], materialIds: ["eva-foam"], toolIds: ["knife", "cutting-mat", "heat-gun", "form"],
    durationLabel: "1 hr", durationMinutes: 60, costLabel: "$20", difficulty: 3, helper: "solo",
    warningIds: ["w-heat", "w-blade"], watchOut: ["A dull blade causes micro-tears and jagged edges that are nearly impossible to hide."],
    completionCriteria: ["Foam holds curved memory."],
    confidence: "strongly-supported", sourceIds: ["s6", "s36"],
  },
  {
    id: "t-cement", checklistId: "006", phaseId: "fabricate", title: "Cement the seam with Barge",
    summary: "Glue the foam edges permanently with Barge contact cement.",
    why: "Barge creates a permanent, highly flexible bond on EVA.",
    instructions: [
      "Go outdoors or into a heavily ventilated garage. Put on the organic vapor respirator.",
      "Apply a thin, even layer of Barge to both mating edges of the seam.",
      "Wait 5–10 minutes until it's dry to the touch (tacky but not wet).",
      "Carefully align the top edges first and press together firmly, working incrementally down the seam.",
    ],
    measurement: "Wait 5–10 min open time",
    prerequisites: ["t-cut-heat"], materialIds: ["barge"], toolIds: ["respirator"], durationLabel: "1 hr", durationMinutes: 60, costLabel: "$25", difficulty: 3, helper: "solo",
    warningIds: ["w-barge", "w-instant-bond"], watchOut: ["Contact cement bonds instantly — realignment is not possible."],
    completionCriteria: ["Seam is permanent."],
    confidence: "confirmed", sourceIds: ["s22", "s37", "s38"],
  },
  {
    id: "t-support-band", phaseId: "fabricate", title: "Fit the 2\" internal support band",
    summary: "A 2\" wide high-density EVA band inside the cone that grips the cranial ridge.",
    why: "The band carries the cone's weight and leverage on bone, not on the glued forehead edge — no harness, skull cap or chinstrap needed.",
    instructions: [
      "Cut a 2\" wide strip of high-density EVA.",
      "Size it to rest snugly around the cranial ridge, passing just above the ears and the brow bone. EVA's slight elasticity lets it grip.",
      "Fix it inside the cone so it acts as the internal cradle.",
      "Test it: the cone should stay stable while walking and with normal head movement.",
    ],
    measurement: "Band width 2\" · sized to head circumference",
    prerequisites: ["t-cement"], materialIds: ["eva-foam", "barge"], toolIds: ["knife", "respirator"], durationLabel: "~45 min (estimate)", durationMinutes: 45, difficulty: 3, helper: "recommended",
    warningIds: ["w-barge"],
    watchOut: ["Research gap: the band is described (Architecture §A) but no attachment step is given. Barge is the research's EVA bond; exact placement requires prototyping."],
    completionCriteria: ["Cone stays put while walking without being held."],
    confidence: "requires-prototyping", sourceIds: ["s9"],
  },
  {
    id: "t-dome", checklistId: "007", phaseId: "fabricate", title: "Sculpt the foam-clay dome tip",
    summary: "Cap the 3–4\" top opening with foam clay and sculpt a parabolic dome.",
    why: "This is what keeps it from looking like a dunce cap. The rounded dome is Beldar's signature.",
    instructions: [
      "Take a tennis-ball-sized piece of EVA foam clay and press it onto the top opening.",
      "Sculpt a smooth, rounded parabolic dome.",
      "Wet your fingers slightly to smooth the clay and blend the transition line into the EVA.",
      "Allow 24–48 hours for the clay to air-dry and cure fully.",
    ],
    measurement: "Clay ≈ tennis-ball size · cure 24–48 h",
    prerequisites: ["t-cement"], materialIds: ["foam-clay"], toolIds: [], durationLabel: "30 mins + 24–48h cure", durationMinutes: 30, costLabel: "$15", difficulty: 3, helper: "solo",
    watchOut: ["Too-sharp tip → wizard hat. Keep the top radius at least 1.5\"."],
    completionCriteria: ["Dome is parabolic & smooth."],
    confidence: "strongly-supported", sourceIds: ["s24"],
  },
  {
    id: "t-silhouette-check", phaseId: "fabricate", title: "Silhouette check (Gate 1 evidence)",
    summary: "Wearer puts on the raw, unpainted cone. Does it read as Beldar?",
    why: "Sealing and paint lock the shape in. Fix shape problems now.",
    instructions: [
      "Wearer puts on the raw EVA structure (no latex, no paint).",
      "Photograph front and side. Compare with the Cone Lab silhouette and the reference.",
      "Check height, taper and dome curve. It should sit flush on the brow and read as Beldar — not generic sci-fi or a party hat.",
      "If it passes, mark Gate 1 passed. If not, see Troubleshooting (wizard hat, tilting).",
    ],
    prerequisites: ["t-dome", "t-support-band"], materialIds: [], toolIds: [], durationLabel: "15 min", durationMinutes: 15, difficulty: 1, helper: "recommended",
    watchOut: [], completionCriteria: ["Gate 1 — Silhouette decided."], sourceIds: [],
  },

  // ── PH-03 Sealing ───────────────────────────────────────────────────
  {
    id: "t-seal", checklistId: "008", phaseId: "seal", title: "Seal with liquid latex",
    summary: "Sand seams lightly, then 3–4 thin coats of liquid latex (or flexible primer).",
    why: "EVA is porous and can't take cosmetics directly. Sealing unifies foam and clay into one skin-like surface.",
    instructions: [
      "Once the clay is fully cured, lightly sand prominent seams with high-grit sandpaper or a rotary tool on low speed.",
      "Coat the entire exterior with three to four thin layers of cosmetic liquid latex or a flexible primer (HexFlex).",
      "Let each layer dry until transparent before applying the next.",
      "Allow 48 hours for total outgassing and curing.",
    ],
    measurement: "3–4 thin layers · 48 h cure",
    prerequisites: ["t-dome"], blockedByGates: ["g-silhouette"], materialIds: ["liquid-latex", "latex-alt"], toolIds: ["sandpaper"],
    durationLabel: "48 hrs", durationMinutes: 120, costLabel: "$18", difficulty: 2, helper: "solo",
    warningIds: ["w-latex"], watchOut: ["Research is inconsistent: construction says 3–4 layers, checklist says 3. Use 3 minimum."],
    completionCriteria: ["Surface is unified & dry."],
    confidence: "strongly-supported", sourceIds: ["s10", "s26"],
  },

  // ── PH-04 Cap Integration ───────────────────────────────────────────
  {
    id: "t-cap-integrate", checklistId: "009", phaseId: "integrate", title: "Cement the Glatzan cap inside the rim",
    summary: "Glue the vinyl cap inside the bottom rim so a skirt hangs below.",
    why: "This is the critical forehead transition — a vinyl skirt whose edge can be melted invisibly into the skin.",
    instructions: [
      "Ventilation + respirator on (Barge).",
      "Turn the sealed cone upside down. Apply contact cement inside the bottom rim, about 1\" deep.",
      "Apply a matching ring of contact cement to the outer crown area of the Glatzan cap.",
      "Once both are tacky, press the cap inside the cone.",
      "You now have a rigid foam cone with a loose vinyl skirt hanging 3–4\" below the rim. The foam rim will rest roughly 1\" above the natural hairline.",
    ],
    measurement: "Cement 1\" deep inside rim · skirt 3–4\" below rim",
    prerequisites: ["t-seal", "t-order-sfx"], materialIds: ["glatzan", "barge"], toolIds: ["respirator"], durationLabel: "1 hr", durationMinutes: 60, costLabel: "$24", difficulty: 3, helper: "solo",
    warningIds: ["w-barge", "w-instant-bond"], watchOut: ["Fix any backward tilt by recutting the base before adhering the cap."],
    completionCriteria: ["Skirt hangs 3 inches below rim."],
    confidence: "strongly-supported", sourceIds: ["s7", "s28"],
  },
  {
    id: "t-comfort-test", phaseId: "integrate", title: "30-minute comfort wear (Gate 2 evidence)",
    summary: "Wear the unglued internal support structure for 30 uninterrupted minutes.",
    why: "Pressure points cause headaches over a 4–6 hour party. Find them now.",
    instructions: [
      "Wearer puts on the unglued cone (support band in place).",
      "Start a 30-minute timer. Walk, sit, turn the head normally.",
      "Note any pressure points, headache, neck strain or hot spots.",
      "If there are none, mark Gate 2 passed.",
    ],
    measurement: "30 uninterrupted minutes",
    prerequisites: ["t-support-band"], materialIds: [], toolIds: [], durationLabel: "30 min", durationMinutes: 30, difficulty: 1, helper: "recommended",
    watchOut: [], completionCriteria: ["Gate 2 — Comfort decided."], sourceIds: [],
  },

  // ── P-2 Skin & Seam Tests ───────────────────────────────────────────
  {
    id: "t-patch-test", checklistId: "010", phaseId: "skin-tests", title: "24-hour patch test",
    summary: "Test Pros-Aide (and liquid latex) on the inner wrist/arm for 24 hours.",
    why: "Verifies no contact dermatitis or allergic reaction before full facial application.",
    instructions: [
      "Apply a small amount of Pros-Aide to the wearer's inner wrist / inner arm. Add a dab of liquid latex nearby (the timeline tests both).",
      "Leave for 24 hours.",
      "Check for redness, itching or hives.",
      "Remove with Super Solv or Isopropyl Myristate — not soap or wipes.",
      "Zero reaction → mark Gate 3 passed. Any reaction → do not proceed; record it in the build log.",
    ],
    measurement: "24 hours",
    prerequisites: ["t-order-sfx"], materialIds: ["pros-aide", "liquid-latex"], toolIds: [], durationLabel: "24 hrs", durationMinutes: 10, costLabel: "$0", difficulty: 1, helper: "solo",
    warningIds: ["w-patch"], watchOut: ["This app can't judge a skin reaction. If in doubt, don't proceed and ask a medical professional."],
    completionCriteria: ["Zero redness or hives."],
    confidence: "confirmed", sourceIds: ["s52"],
  },
  {
    id: "t-acetone-practice", phaseId: "skin-tests", title: "Acetone-melt practice (Prototype 2)",
    summary: "Helper practices melting a scrap Glatzan edge on the forearm.",
    why: "The go/no-go gate. The helper must master dissolving vinyl without turning it into a gummy, stringy mess.",
    instructions: [
      "Glue a spare piece of Glatzan cap edge to the wearer's forearm (or an assistant's forehead) with Pros-Aide. Wait until it's completely clear.",
      "Dip a cotton swab or small firm brush in 100% acetone — minimal liquid.",
      "Gently swipe along the extreme outer edge. The vinyl should melt into a microscopic feathered taper.",
      "Stipple a little PAX over it to see how it reads.",
      "Remove with Super Solv / Isopropyl Myristate.",
    ],
    prerequisites: ["t-order-sfx"], blockedByGates: ["g-patch"], materialIds: ["glatzan", "pros-aide", "acetone"], toolIds: ["swabs", "detail-brush"],
    durationLabel: "2 hrs", durationMinutes: 120, difficulty: 4, helper: "required", defaultRole: "helper",
    warningIds: ["w-acetone", "w-wet-prosaide"],
    watchOut: ["A visible white crust = too much Pros-Aide, or not enough acetone during the melt."],
    completionCriteria: ["The vinyl edge becomes completely invisible to the naked eye."],
    confidence: "strongly-supported", sourceIds: ["s7", "s59"],
    referenceLink: { label: "Kryolan / FormX SFX tutorials", url: "https://www.formx.nl/p/category/8f129acd-dd51-48e9-bf97-ced114499bd6?setlanguage=en" },
  },
  {
    id: "t-mix-pax", checklistId: "011", phaseId: "skin-tests", title: "Mix PAX paint",
    summary: "1 part Pros-Aide : 1 part Liquitex, tinted to match the wearer's neck.",
    why: "PAX is a flexible, crack-proof base that bonds to foam, latex, vinyl and skin. Standard paint or foundation cracks.",
    instructions: [
      "Mix 1 part Pros-Aide (preferably No-Tack) with 1 part Liquitex Heavy Body acrylic.",
      "Pigment: Titanium White, a small amount of Yellow Ochre, and a micro-drop of Burnt Sienna.",
      "Aim for a pale, slightly jaundiced flesh tone that matches the wearer's neck and chest.",
      "Record the ratio you landed on in Makeup Station → Practice tests.",
    ],
    measurement: "1 : 1 Pros-Aide : acrylic",
    prerequisites: ["t-order-sfx"], materialIds: ["pros-aide", "liquitex", "pros-aide-notack"], toolIds: [], durationLabel: "30 mins", durationMinutes: 30, costLabel: "$20", difficulty: 2, helper: "solo",
    warningIds: ["w-pax-heat"], watchOut: ["Do not accelerate PAX drying with high heat — it stays permanently tacky."],
    completionCriteria: ["Color matches wearer's neck."],
    confidence: "strongly-supported", sourceIds: ["s17", "s21", "s40"],
  },
  {
    id: "t-paint-test", phaseId: "skin-tests", title: "Paint test: PAX + powder + RMGP",
    summary: "Practice the full paint sequence on the sealed cone or a test area.",
    why: "Prototype 2 includes PAX paint. Practicing the powder and mottling steps avoids surprises on the night.",
    instructions: [
      "Stipple PAX with a dense sponge.",
      "Press translucent powder in heavily with a velour puff; dust off with a fluffy brush.",
      "Stipple sheer warm reds and subtle purples of RMGP with a torn sponge.",
      "Try a few faint blue/red capillaries with a fine brush.",
      "Log the products, mix and result in Makeup Station.",
    ],
    prerequisites: ["t-mix-pax"], materialIds: ["setting-powder", "rmgp"], toolIds: ["sponges", "puff-brush", "detail-brush"],
    durationLabel: "1 hr (estimate)", durationMinutes: 60, difficulty: 3, helper: "recommended",
    warningIds: ["w-oil-latex"], watchOut: ["Skipping powder: PAX stays tacky and sticks to itself and clothing."],
    completionCriteria: ["Paint is flexible, matte after powder, and the mottling reads as skin."],
    confidence: "strongly-supported", sourceIds: ["s17", "s19"],
    referenceLink: { label: "Open Makeup Station", url: "/makeup" },
  },
  {
    id: "t-seam-photo", phaseId: "skin-tests", title: "Flash photo the seam (Gate 5 evidence)",
    summary: "Photograph the melted, painted test edge under harsh flash.",
    why: "Flash exposes ridges and shadow lines the eye misses. The system isn't solved until it passes.",
    instructions: [
      "On the practice edge (forearm/forehead) after melt and paint, take photos with direct camera flash.",
      "Look for a distinct shadow line at the transition.",
      "No line → mark Gate 5 passed. Visible line → see Troubleshooting: 'Forehead edge is visible'.",
    ],
    prerequisites: ["t-acetone-practice", "t-paint-test"], materialIds: [], toolIds: [], durationLabel: "10 min", durationMinutes: 10, difficulty: 1, helper: "recommended",
    watchOut: [], completionCriteria: ["Gate 5 — Seam Photography decided."], sourceIds: [],
  },
  {
    id: "t-prepaint", phaseId: "skin-tests", title: "Pre-paint the upper cone",
    summary: "Base-coat the upper cone with PAX to save time on application day.",
    why: "Application day is tight (3 hours). Pre-painting the parts that never touch skin frees up the helper.",
    instructions: [
      "Stipple PAX over the upper portions of the cone (not the vinyl skirt or the transition zone).",
      "Powder heavily; dust off.",
      "Let it dry naturally — no high heat.",
    ],
    prerequisites: ["t-mix-pax", "t-cap-integrate"], materialIds: ["setting-powder"], toolIds: ["sponges", "puff-brush"],
    durationLabel: "1 hr (estimate)", durationMinutes: 60, difficulty: 2, helper: "solo",
    warningIds: ["w-pax-heat"], watchOut: [], completionCriteria: ["Upper cone evenly base-coated and powdered."],
    sourceIds: ["s17"],
  },

  // ── PH-05 Wardrobe ──────────────────────────────────────────────────
  {
    id: "t-source-clothing", checklistId: "003", phaseId: "wardrobe", title: "Source overalls & shirt",
    summary: "Procure Liberty (or Round House) overalls and a 90s abstract rayon shirt.",
    why: "The fireworks-scene look is far more recognizable and party-practical than the gray jumpsuits.",
    instructions: [
      "Overalls: classic men's rigid denim bib overalls, medium wash. Liberty (green zipper accents) or Round House.",
      "Size by maximum belly circumference: add 4–6\" to the wearer's normal jean waist.",
      "Shirt: prioritize an authentic 1990s rayon short-sleeve camp-collar shirt with a chaotic black/white abstract pattern (eBay, Etsy, Grailed, Depop).",
      "Use the saved search phrases in Wardrobe.",
    ],
    measurement: "Overall size = jean waist + 4–6\"",
    prerequisites: [], materialIds: [], toolIds: [], durationLabel: "2 hrs", durationMinutes: 120, costLabel: "~$70", difficulty: 2, helper: "solo",
    watchOut: ["Slim-fit or dark raw indigo denim looks modern/trendy."], completionCriteria: ["Garments acquired."],
    confidence: "strongly-supported", sourceIds: ["s42", "s43", "s45", "s50"],
    referenceLink: { label: "Open Wardrobe", url: "/wardrobe" },
  },
  {
    id: "t-wardrobe-fit", phaseId: "wardrobe", title: "Try-on & hardware check",
    summary: "Check drape, fit, and that the strap hardware can't scrape the forehead edge.",
    why: "Bib straps unbuckle at the shoulder for bathroom trips; the metal can snag the delicate prosthetic edge.",
    instructions: [
      "Try the overalls and shirt together. The overalls should be baggy and utilitarian; the shirt should fall softly under the straps.",
      "Practice unbuckling and re-buckling the shoulder straps. Note how close the hardware comes to the forehead/temple.",
      "Pick footwear: 90s brown leather loafers or chunky white dad sneakers.",
    ],
    prerequisites: ["t-source-clothing"], materialIds: [], toolIds: [], durationLabel: "30 min", durationMinutes: 30, difficulty: 1, helper: "solo",
    warningIds: ["w-neck"], watchOut: ["Stiff cotton poplin bunches incorrectly under the straps."],
    completionCriteria: ["Outfit fits; strap re-buckling practiced."], sourceIds: ["s46"],
  },

  // ── PH-06 Rehearsal ─────────────────────────────────────────────────
  {
    id: "t-rehearsal", phaseId: "rehearsal", title: "2-hour full dress rehearsal",
    summary: "Unglued headpiece + full outfit, at least 2 hours walking and sitting.",
    why: "Do NOT make Halloween night the first full test. Find heat, balance and neck strain problems now.",
    instructions: [
      "Open Rehearsal Mode and start the timer.",
      "Wear the unglued headpiece with the overalls and shirt.",
      "Walk, sit, take stairs, go through doorways, practice hugs without impaling anyone.",
      "Answer the 15 / 30 / 60 / 120-minute checkpoints.",
      "Get a GO / GO WITH FIXES / NO-GO summary.",
    ],
    measurement: "≥ 2 hours",
    prerequisites: ["t-cap-integrate", "t-wardrobe-fit"], materialIds: [], toolIds: [], durationLabel: "2+ hrs", durationMinutes: 120, difficulty: 2, helper: "recommended",
    watchOut: [], completionCriteria: ["Rehearsal verdict recorded."], sourceIds: [],
    referenceLink: { label: "Open Rehearsal Mode", url: "/rehearsal" },
  },
  {
    id: "t-transport", phaseId: "rehearsal", title: "Decide the transport plan",
    summary: "Apply on-site, or travel in a vehicle with substantial headroom.",
    why: "The cone adds nearly a foot of height. Car roofs crush cones and lift edges.",
    instructions: [
      "Preferred: travel to the venue before the adhesion process and apply on-site.",
      "If applying at home: use a vehicle with substantial headroom (SUV, truck, minivan) with the passenger seat fully reclined.",
    ],
    prerequisites: [], materialIds: [], toolIds: [], durationLabel: "10 min", durationMinutes: 10, difficulty: 1, helper: "solo",
    watchOut: [], completionCriteria: ["Plan agreed and written in the build log."], sourceIds: [],
  },
  {
    id: "t-kit", phaseId: "rehearsal", title: "Pack the 60-second repair kit",
    summary: "Ziplock bag for the front overall pocket.",
    why: "If an edge lifts from sweat, the wearer can fix it in a minute.",
    instructions: [
      "Q-tips.",
      "1 oz travel bottle of Pros-Aide.",
      "A small cosmetic sponge pre-loaded with translucent setting powder.",
      "Put it all in a small ziplock bag in the front overall pocket.",
    ],
    prerequisites: ["t-order-sfx"], materialIds: ["kit-bag", "pros-aide", "setting-powder"], toolIds: ["swabs", "sponges"], durationLabel: "10 min", durationMinutes: 10, difficulty: 1, helper: "solo",
    watchOut: ["Research gap: the kit has no remover. Decide whether to also carry Super Solv / Isopropyl Myristate for emergencies."],
    completionCriteria: ["Kit packed in the overall pocket."], sourceIds: [],
  },

  // ── PH-07 Halloween ─────────────────────────────────────────────────
  {
    id: "t-hair-skin", checklistId: "012", phaseId: "deploy", title: "Hair & skin prep",
    summary: "Strip oils, apply Skin Prep Pro, gel hair flat.",
    why: "Oils and sweat break the acrylic bond. Skin Prep Pro is the antiperspirant barrier that makes it last.",
    instructions: [
      "Wearer washes face, forehead and temples thoroughly with astringent or witch hazel to strip natural oils.",
      "Helper applies Mehron Skin Prep Pro to the upper forehead and temples.",
      "Wearer flattens hair against the skull with strong-hold, alcohol-free gel and combs it flat. Long hair: braid tightly and pin to the nape.",
    ],
    measurement: "T-180 min (5:00 PM)",
    prerequisites: ["t-patch-test"], materialIds: ["skin-prep", "astringent", "hair-gel"], toolIds: [], durationLabel: "30 mins", durationMinutes: 30, costLabel: "$14", difficulty: 1, helper: "required",
    watchOut: [], completionCriteria: ["Skin is oil-free and matte."], confidence: "confirmed", sourceIds: ["s34", "s28"],
  },
  {
    id: "t-fit-trace", phaseId: "deploy", title: "Position & mark the trim line",
    summary: "Wearer dons the cone; helper traces hairline, brow ridge and ears onto the vinyl.",
    why: "The skirt has to be trimmed to this exact head, with clearance around the ears.",
    instructions: [
      "Pull the structure carefully over the head. The foam rim sits securely on the upper forehead; the vinyl skirt pulls down tautly over the eyebrows, temples and ears.",
      "Helper traces the natural hairline, brow ridge and ears onto the vinyl with a washable cosmetic marker.",
      "Remove the cone. Trim away excess vinyl, leaving a 1\" gluing margin beyond the visual transition line.",
    ],
    measurement: "Leave 1\" gluing margin · T-150 min",
    prerequisites: ["t-hair-skin", "t-cap-integrate"], materialIds: [], toolIds: ["marker"], durationLabel: "30 min", durationMinutes: 30, difficulty: 3, helper: "required",
    watchOut: ["Ensure clearance around the ears — they stay exposed."], completionCriteria: ["Skirt trimmed with a 1\" margin and ear clearance."],
    sourceIds: ["s28"],
  },
  {
    id: "t-trim-glue", checklistId: "013", phaseId: "deploy", title: "Glue the cap",
    summary: "Pros-Aide in 2\" sections, wait until clear, press firmly.",
    why: "The bond is what keeps the edge down all night.",
    instructions: [
      "Re-seat the cap onto the prepared skin.",
      "Work in small 2\" sections: thin layer of Pros-Aide on the skin and on the matching underside of the vinyl.",
      "Wait 3–5 minutes until the Pros-Aide turns completely clear. This is critical.",
      "Press the vinyl firmly into the skin, ensuring no wrinkles form.",
    ],
    measurement: "2\" sections · 3–5 min until clear · T-120 min",
    prerequisites: ["t-cap-integrate", "t-hair-skin", "t-fit-trace"], blockedByGates: ["g-comfort", "g-patch"], materialIds: ["pros-aide"], toolIds: [],
    durationLabel: "45 mins", durationMinutes: 45, costLabel: "$0", difficulty: 4, helper: "required", defaultRole: "helper",
    warningIds: ["w-wet-prosaide"], watchOut: ["Wet, white Pros-Aide traps moisture and will not stick."],
    completionCriteria: ["Cap is firmly attached without wrinkles."], confidence: "confirmed", sourceIds: ["s39", "s4"],
  },
  {
    id: "t-acetone-melt", checklistId: "014", phaseId: "deploy", title: "Acetone melt",
    summary: "Dissolve the vinyl edge into the skin with acetone on a swab.",
    why: "The melt turns the edge into a microscopic taper — the zero-ridge transition that sells the illusion.",
    instructions: [
      "High ventilation. Wearer keeps eyes tightly closed.",
      "Dip a cotton swab or small firm brush into 100% acetone — minimal liquid.",
      "Gently swipe along the extreme outer edge of the glued vinyl.",
      "The vinyl melts into a feathered taper that fuses with the skin.",
    ],
    measurement: "T-90 min (6:30 PM)",
    prerequisites: ["t-trim-glue"], blockedByGates: ["g-melt"], materialIds: ["acetone"], toolIds: ["swabs", "detail-brush"],
    durationLabel: "15 mins", durationMinutes: 15, costLabel: "$6", difficulty: 5, helper: "required", defaultRole: "helper",
    warningIds: ["w-acetone"], watchOut: ["Prevent liquid acetone from running toward the eyes."],
    completionCriteria: ["Edge is totally invisible."], confidence: "strongly-supported", sourceIds: ["s7", "s59"],
  },
  {
    id: "t-paint", checklistId: "015", phaseId: "deploy", title: "Paint & mottle",
    summary: "Stipple PAX, powder heavily, RMGP mottling, face integration, barrier spray.",
    why: "PAX bridges foam, latex, vinyl and skin; RMGP makes it look alive.",
    instructions: [
      "Stipple PAX over the melted edge, the cap and down onto the natural forehead, stopping just above the eyes.",
      "Powder immediately and heavily with a velour puff; dust off excess.",
      "RMGP: sheer warm reds and subtle purples with a torn sponge — temples, back of neck, sides of cone.",
      "Fine brush: faint translucent blue and red capillaries near the temporal transition zones; light brown freckles across the dome.",
      "Highlight the front vertical ridge of the cone with a lighter flesh tone (mixed with white RMGP).",
      "Wearer blends creme foundation (matched to the RMGP tones) on the lower face, neck and ears.",
      "Mist the entire face and cone with Mehron Barrier Spray.",
    ],
    measurement: "T-75 → T-15 min",
    prerequisites: ["t-mix-pax", "t-acetone-melt"], materialIds: ["setting-powder", "rmgp", "creme-palette", "barrier-spray"], toolIds: ["sponges", "puff-brush", "detail-brush"],
    durationLabel: "45 mins", durationMinutes: 45, costLabel: "$42", difficulty: 4, helper: "required", defaultRole: "helper",
    warningIds: ["w-oil-latex"], watchOut: [], completionCriteria: ["Makeup matches lower face."], confidence: "strongly-supported", sourceIds: ["s17", "s19"],
    referenceLink: { label: "Paint map", url: "/makeup#paint-map" },
  },
  {
    id: "t-dress", phaseId: "deploy", title: "Dress & final checks",
    summary: "Step into the overalls, button the shirt, mobility check, flash photo, hydrate.",
    why: "Dressing last protects the paint. The flash photo catches seam problems before you leave.",
    instructions: [
      "Wearer carefully steps into the overalls and buttons the abstract shirt. Do not pull anything tight-necked over the appliance.",
      "Final mobility check.",
      "Photograph under bright flash to verify seam invisibility.",
      "Hydrate the wearer. Repair kit in the front pocket.",
    ],
    measurement: "T-15 → T-0 (8:00 PM)",
    prerequisites: ["t-paint"], materialIds: [], toolIds: [], durationLabel: "15 min", durationMinutes: 15, difficulty: 1, helper: "recommended",
    warningIds: ["w-neck", "w-dehydration"], watchOut: [], completionCriteria: ["Approved for deployment."], sourceIds: [],
    referenceLink: { label: "Open Halloween Mode", url: "/halloween" },
  },
  {
    id: "t-removal", checklistId: "016", phaseId: "deploy", title: "Safe removal",
    summary: "Lift edges with Super Solv or Isopropyl Myristate — never rip dry.",
    why: "Ripping Pros-Aide off dry causes severe skin tearing, blistering and contact dermatitis.",
    instructions: [
      "Helper saturates a cotton swab or soft brush with Super Solv (or Isopropyl Myristate).",
      "Gently work remover under the edge of the vinyl. Give it 15–30 seconds.",
      "Slowly roll the cap backward, continuously brushing remover into the newly exposed adhesive. Do not force the pull.",
      "Massage remaining Isopropyl Myristate or coconut oil into the skin to dissolve residual tack.",
      "Wash with warm water and a gentle cleanser, then a heavy moisturizer.",
      "The vinyl skirt will likely be destroyed — normal. The EVA cone is reusable: cut out the old vinyl and cement in a new cap.",
    ],
    measurement: "15–30 s dwell per section",
    prerequisites: ["t-dress"], materialIds: ["super-solv", "ipm", "aftercare"], toolIds: ["swabs"], durationLabel: "30 mins", durationMinutes: 30, costLabel: "$28", difficulty: 2, helper: "required", defaultRole: "helper",
    warningIds: ["w-rip"], watchOut: ["Micellar water, makeup wipes and soap are ineffective — don't scrub."],
    completionCriteria: ["Skin is clean and undamaged."], confidence: "confirmed", sourceIds: ["s39", "s54", "s55", "s56"],
  },
];

export const taskById = Object.fromEntries(tasks.map((t) => [t.id, t])) as Record<string, Task>;
export const tasksByPhase = (phaseId: string) => tasks.filter((t) => t.phaseId === phaseId);
